//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVStaffing.LocalResource.Home.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVStaffing.LocalResource.Home.Index.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Cookies.
        /// </summary>
        internal static string AcceptCookiesLabel {
            get {
                return ResourceManager.GetString("AcceptCookiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        internal static string AddActionLabel {
            get {
                return ResourceManager.GetString("AddActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        internal static string AdvanceOptionsLabel {
            get {
                return ResourceManager.GetString("AdvanceOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Registered?.
        /// </summary>
        internal static string AlreadyRegisterLabel {
            get {
                return ResourceManager.GetString("AlreadyRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Value.
        /// </summary>
        internal static string BestValueLabel {
            get {
                return ResourceManager.GetString("BestValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Size.
        /// </summary>
        internal static string ChangeSize {
            get {
                return ResourceManager.GetString("ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Type.
        /// </summary>
        internal static string CompareType {
            get {
                return ResourceManager.GetString("CompareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Account?.
        /// </summary>
        internal static string CreateNewAccountLabel {
            get {
                return ResourceManager.GetString("CreateNewAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Javascript.
        /// </summary>
        internal static string DisableJavascriptLabel {
            get {
                return ResourceManager.GetString("DisableJavascriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Compare.
        /// </summary>
        internal static string ElementCompare {
            get {
                return ResourceManager.GetString("ElementCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string GoButton {
            get {
                return ResourceManager.GetString("GoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string LeadInterval {
            get {
                return ResourceManager.GetString("LeadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LeadName {
            get {
                return ResourceManager.GetString("LeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Job Title.
        /// </summary>
        internal static string LeadPlaceholder {
            get {
                return ResourceManager.GetString("LeadPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Folds.
        /// </summary>
        internal static string PageFoldsLabel {
            get {
                return ResourceManager.GetString("PageFoldsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device.
        /// </summary>
        internal static string PageFoldsPlaceholder {
            get {
                return ResourceManager.GetString("PageFoldsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Actions.
        /// </summary>
        internal static string PerformActionsLabel {
            get {
                return ResourceManager.GetString("PerformActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per month.
        /// </summary>
        internal static string PerMonthLabel {
            get {
                return ResourceManager.GetString("PerMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Proxy.
        /// </summary>
        internal static string ProxyPlaceholder {
            get {
                return ResourceManager.GetString("ProxyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size By Device.
        /// </summary>
        internal static string ScreenSizeByDeviceLabel {
            get {
                return ResourceManager.GetString("ScreenSizeByDeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string ScreenSizePlaceholder {
            get {
                return ResourceManager.GetString("ScreenSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        internal static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 class=&quot;text-uppercase font-weight-bold&quot;&gt;Retrieving the page...&lt;/h4&gt;
        ///
        ///                                    &lt;p class=&quot;font-italic text-muted&quot;&gt;Click in Advanced for more options like: &lt;/p&gt;
        ///                                    &lt;ul&gt;
        ///                                        &lt;li&gt;Click a button or filling a form&lt;/li&gt;
        ///                                        &lt;li&gt;Only alert me if a keyword is added&lt;/li&gt;
        ///                                        &lt;li&gt;Monitor only the text or selected element&lt;/li&gt;
        ///                  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spinner {
            get {
                return ResourceManager.GetString("Spinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Monitoring.
        /// </summary>
        internal static string StartMonitoringLabel {
            get {
                return ResourceManager.GetString("StartMonitoringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Compare.
        /// </summary>
        internal static string TextCompare {
            get {
                return ResourceManager.GetString("TextCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to fetch the web page.
        /// </summary>
        internal static string UnableToFetchWebPageMessage {
            get {
                return ResourceManager.GetString("UnableToFetchWebPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Url.
        /// </summary>
        internal static string WebsiteUrl {
            get {
                return ResourceManager.GetString("WebsiteUrl", resourceCulture);
            }
        }
    }
}
